services:
  - type: web
    name: hyojin-system
    runtime: python
    buildCommand: apt-get update && apt-get install -y libreoffice-calc && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
